#!/bin/sh
# This hook is used to push a mirrored version of all committed files to your remote repo after they are commited

# Replace this variable with your remote repo name
echo
echo "==== post commit  ===="
echo
